### ISSUE TITLE
firefox(66) <-> chrome p2p: firefox get error message when chrome publish localStream to firefox

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#119] opened 2019-03-30 02:41 UTC
1: chrome and firefox connect server
2: chrome and firefox addRemoteId each other
3: firefox publish localstream to chrome will success
4: chrome publish local stream to firefox 

expect : chrome publish success and firefox show remote stream good

error log:
About to set remote description. Signaling state: stable owt.js:9:79291
Signaling state changed: have-remote-offer owt.js:9:83050
Remote track added. owt.js:9:80524
Draining pending streams. owt.js:9:86010
Current description: [object RTCSessionDescription] owt.js:9:90779
Pending description: null owt.js:9:90852
Signaling state changed: stable owt.js:9:83050
Draining pending streams. owt.js:9:86010
Peer connection is ready for draining pending streams. owt.js:9:86101
Draining pending messages. owt.js:9:87455
Empty candidate. owt.js:9:80441
Received woogeen message. sc.websocket.js:118:7
Received signaling message from 12: {"type":"chat-closed","data":{"stack":"Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to apply the description for 0: Failed to set SSL role for the transport.","message":"Error happened at remote side."}} owt.js:9:67121
Channel received message: [object Object] owt.js:9:76185
Stream is removed. peercall.html:237:9
Signaling state changed: closed owt.js:9:83050
Remote stream removed. owt.js:9:82154
Received woogeen message. sc.websocket.js:118:7
Received signaling message from 12: {"type":"chat-closed","data":{"code":2500,"message":"Error happened at remote side."}} owt.js:9:67121
AbortError: The fetching process for the media resource was aborted by the user agent at the user's request.

**Comment by jianjunz** [comment] 2019-09-27 06:13
Cannot reproduce on Firefox 69 and Chrome 77. I think this issue has been fixed in the latest master branch.

**Closed by jianjunz** 2019-09-27 06:13 UTC
