### ISSUE TITLE
iOS/iPad 13.4.1, ice procedure failed in conference calls with MCU v4.3

### ISSUE THREAD

**Issue by MrSmith87** [open-webrtc-toolkit/owt-client-javascript#343] opened 2020-04-12 03:44 UTC
Hello Team,
Conference call doesn't seem to work with Safari in Iphone and Ipads running the latest iOS v13.4.1. I can easily recreate it everytime atleast with iphone 11 and ipad (6th gen). I also tried running your sample (samplertcservice.js) application  which gives the same error.

I am attaching both the JS console logs and socket logs for your reference.
Request your kind attention as it is very critical to us.

Thanks in anticipation.
[socket.io logs.pdf](https://github.com/open-webrtc-toolkit/owt-client-javascript/files/4465820/socket.io.logs.pdf)
<img width="1440" alt="console logs screenshot" src="https://user-images.githubusercontent.com/23348651/79059988-b36a0180-7c9d-11ea-8bcf-cd6227118845.png">

Regards
Sumit

**Comment by jianjunz** [comment] 2020-04-12 11:51
Hi Sumit,

Thanks for reporting this issue. The root cause of this issue is server side lacks TLS 1.2 support. It's expected to be fixed by https://github.com/open-webrtc-toolkit/owt-server/pull/466.

**Comment by MrSmith87** [comment] 2020-04-12 11:55
Thanks a lot for the prompt response.
do you mean to say If I clone and install the latest master branch in our MCU server, then it should work fine?

**Closed** 2020-04-12 16:21 UTC
